---
title: "publicly funded stadiums data"
author: "Dylan Manfre"
date: "2023-02-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#libraries
library(tidyverse)
library(tidycensus)
library(janitor)
library(lubridate)
#install.packages("ipumsr")
library(ipumsr)

```

```{r}

# Load Census API key

Sys.setenv(CENSUS_API_KEY = "5cb2b9c628a1d1329c5bf4d36fe4435c6501efc8", overwrite = TRUE)

# is using acs 5'
#when writing this make it say that these numbers are based on five-year rolling averages...


```

```{r}

#Reference tables

#Load ACS crosswalk

ACS_5 <- load_variables(2020, "acs5")
#What is the difference between the ACS and the ACS5?

# List of MD cities
md_cities <- get_acs(geography = "place",
              variables = c(medi_house_income = "B19013_001"),
              state = "MD")

# Load census crosswalks
census_2000_1 <- load_variables(2000, "sf1")
census_2000_2 <- load_variables(2000, "sf2")
census_2000 <-  bind_rows(census_2000_1, census_2000_2)
rm(census_2000_1, census_2000_2)

census_2010_1 <- load_variables(2010, "sf1")
census_2010_2 <- load_variables(2010, "sf2")
census_2010 <-  bind_rows(census_2010_1, census_2010_2)
rm(census_2010_1, census_2010_2)

#census_1990_1 <- load_variables(1990, "sf1")

```


```{r}

# ALL DATA

#Hagerstown
h_2021 <- get_acs(geography = "place",
              variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            education_total = "B15003_001",
                            education_hs = "B15003_017",
                            education_bachelors = "B15003_022",
                            public_assistance_total = "B22003_001",
                            public_assistance_received = "B22003_002",
                            public_assistance_not_received = "B22003_005",
                            poverty_total = "B17020_001",
                            poverty_below = "B17020_002",
                            poverty_above = "B17020_010",
                            rent = "B25064_001"),
              state = "MD",
              year = 2021) %>% 
  filter(NAME == "Hagerstown city, Maryland") %>% 
  mutate(year = 2021)
 
#Frederick - will likely use 1990 + 2021
#We would like 1990 because that's when the ballpark opened; how do we do this?
f_2021 <- get_acs(geography = "place", 
              variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            education_total = "B15003_001",
                            education_hs = "B15003_017",
                            education_bachelors = "B15003_022",
                            public_assistance_total = "B22003_001",
                            public_assistance_received = "B22003_002",
                            public_assistance_not_received = "B22003_005",
                            poverty_total = "B17020_001",
                            poverty_below = "B17020_002",
                            poverty_above = "B17020_010",
                            rent = "B25064_001"),
              state = "MD",
              year = 2021) %>% 
  filter(NAME == "Frederick city, Maryland") %>% 
  mutate(year = 2021)

#Waldorf - need 2008 + 2021
w_2021 <- get_acs(geography = "place",
                variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            education_total = "B15003_001",
                            education_hs = "B15003_017",
                            education_bachelors = "B15003_022",
                            public_assistance_total = "B22003_001",
                            public_assistance_received = "B22003_002",
                            public_assistance_not_received = "B22003_005",
                            poverty_total = "B17020_001",
                            poverty_below = "B17020_002",
                            poverty_above = "B17020_010",
                            rent = "B25064_001"),              
              state = "MD",
              year = 2021) %>% 
  filter(NAME == "Waldorf CDP, Maryland") %>% 
  mutate(year = 2021)

#Bowie - need 1994 + 2021
bo_2021 <- get_acs(geography = "place",
              variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            education_total = "B15003_001",
                            education_hs = "B15003_017",
                            education_bachelors = "B15003_022",
                            public_assistance_total = "B22003_001",
                            public_assistance_received = "B22003_002",
                            public_assistance_not_received = "B22003_005",
                            poverty_total = "B17020_001",
                            poverty_below = "B17020_002",
                            poverty_above = "B17020_010",
                            rent = "B25064_001"),
              state = "MD",
              year = 2021) %>% 
  filter(NAME == "Bowie city, Maryland") %>% 
  mutate(year = 2021)

#Salisbury - need 1996 + 2021
s_2021 <- get_acs(geography = "place",
variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            education_total = "B15003_001",
                            education_hs = "B15003_017",
                            education_bachelors = "B15003_022",
                            public_assistance_total = "B22003_001",
                            public_assistance_received = "B22003_002",
                            public_assistance_not_received = "B22003_005",
                            poverty_total = "B17020_001",
                            poverty_below = "B17020_002",
                            poverty_above = "B17020_010",
                            rent = "B25064_001"),      state = "MD",
              year = 2021) %>% 
  filter(NAME == "Salisbury city, Maryland") %>% 
  mutate(year = 2021)

#Baltimore - need 1992 + 2021
ba_2021 <- get_acs(geography = "place",
variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", #there is an error here saying this one was not found...
                            labor_unemployed = "B23025_005",
                            education_total = "B15003_001",
                            education_hs = "B15003_017",
                            education_bachelors = "B15003_022",
                            public_assistance_total = "B22003_001",
                            public_assistance_received = "B22003_002",
                            public_assistance_not_received = "B22003_005",
                            poverty_total = "B17020_001",
                            poverty_below = "B17020_002",
                            poverty_above = "B17020_010",
                            rent = "B25064_001"),
state = "MD",
              year = 2021) %>% 
  filter(NAME == "Baltimore city, Maryland") %>% 
  mutate(year = 2021)

#Aberdeen - need 2002 + 2021
a_2021 <- get_acs(geography = "place",
variables = c(medi_house_income = "B19013_001", 
                            population = "B01003_001", 
                            medi_home_value = "B25077_001", 
                            housing_total = "B25002_001",
                            housing_occupied = "B25002_002",
                            housing_vacancies = "B25002_003", 
                            labor_total = "B23025_003", 
                            labor_employed = "B23025_004", 
                            labor_unemployed = "B23025_005",
                            education_total = "B15003_001",
                            education_hs = "B15003_017",
                            education_bachelors = "B15003_022",
                            public_assistance_total = "B22003_001",
                            public_assistance_received = "B22003_002",
                            public_assistance_not_received = "B22003_005",
                            poverty_total = "B17020_001",
                            poverty_below = "B17020_002",
                            poverty_above = "B17020_010",
                            rent = "B25064_001"),
state = "MD",
              year = 2021) %>% 
  filter(NAME == "Aberdeen city, Maryland") %>% 
  mutate(year = 2021)

#Combine all 2021 income
#all_income_2021 <-  bind_rows()

#exporting them to CSV
#write_csv(htown_medi_house_income, file = "htown_medi_house_income.csv")
#write_csv(htown_medi_house_income, file = "fred_medi_house_income.csv")


```

```{r}

#TESTING DICENNIAL CENSUS

#get_decennial()

```

```{r}
### Trying to get employment data####

B23025_004 == "Estimate!!Total:!!In labor force:!!Civilian labor force:!!Employed"

get_acs(geography = "place",
              variables = c(civil_labor_total = "B23025_003", employed = "B23025_004", unemployed = "B23025_005"),
              state = "MD",
              year = 2021) %>% 
  filter(NAME == "Hagerstown city, Maryland") %>% 
  mutate(year = 2021)

```

```{r}

### Maybe here we can look at employment data to get a percentage of how many people are employed vs not. ###

### Maybe also worth looking at how many people work remotely vs in person ... may not be an important metroc cuz none of these cities are real metro areas. 



```

```{r}
### Maybe we can take a look here and see how many people have Bachelor's Degrees vs Not ### 

##Use this section to look at Education Data##

#Total HS grad (includes equivlency)
get_acs(geography = "place",
              variables = c(BAdegreee = "B06009_005"),
              state = "MD",
              year = 2021) %>% 
  filter(NAME == "Hagerstown city, Maryland") %>% 
  mutate(year = 2021)
#This says only 3506 people have bachelor's degrees in Hagerstown... pretty low. 

#B29002_005 Estimate!!Total:!!Some college, no degree

get_acs(geography = "place",
              variables = c(some_college_no_degree = "B29002_005"),
              state = "MD",
              year = 2021) %>% 
  filter(NAME == "Hagerstown city, Maryland") %>% 
  mutate(year = 2021)
## 7035 people in Hagerstown with some college experience but no degree.
```


```{r}
## Is it worth getting these numbers of people who are enrolled in certain grade levels? Could be interesting to see because these people may be the ones working at the ballpark##

B14007_001 ==SCHOOL ENROLLMENT BY DETAILED  LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER

grade_9_to_12 <- get_acs(geography = "place",
              variables = c(total_school_enrolled = "B14007_002",
                            grade_9 = "B14007_013",
                            grade_10 = "B14007_014",
                            grade_11 = "B14007_015",
                            grade_12 = "B14007_016"
                            ),
              state = "MD",
              year = 2021) %>% 
  filter(NAME == "Hagerstown city, Maryland") %>% 
  mutate(year = 2021)
```


```{r}
## Gathering codes for real estate taxes. 


B25103_001 = median real estate taxes paid - total
B25090_001 = Estimate!!Aggregate real estate taxes paid (dollars):

  get_acs(geography = "place",
              variables = c(medi_real_estate_tax = "B25103_001" ),
              state = "MD",
              year = 2021) %>% 
  filter(NAME == "Hagerstown city, Maryland") %>% 
  mutate(year = 2021)

#write_csv(grade_9_to_12, file = "grade_9_to_12.csv")

```

#graduate or professional degree
 get_acs(geography = "place",
              variables = c(gradOprodegree = "B06009_006"),
              state = "MD",
              year = 2021) %>% 
  filter(NAME == "Hagerstown city, Maryland") %>% 
  mutate(year = 2021)

```
